name: Go

on:
  push:
    branches: [ "main" ]
  pull_request_target:
        branches: [ "main" ]
        types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Build
      run: go build -o differ
