name: Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        provenance: false
        context: .
        file: Containerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.repository == 'Vanilla-OS/Differ' && github.ref == 'refs/heads/main' }}
        tags: ghcr.io/vanilla-os/differ:main
